# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    pusher:
        class:  AppBundle\Service\TriggerPusher
        arguments: ["%pusher_key%", "%pusher_secret%", "%pusher_app_id%"]
    acme_api.event.jwt_created_listener:
        class: AppBundle\EventListener\JWTCreatedListener
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onJWTCreated }
