# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    pusher:
        class:  Appbundle\Service\TriggerPusher
        arguments: ["%pusher_key%", "%pusher_secret%", "%pusher_app_id%"]
